name: Release

on:
  push:
    branches: ['main']
    tags: [v*]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.2.2]
        java: [temurin@11]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v2

      - run: sbt ++${{ matrix.scala }} Universal/stage

      - id: release_tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        run: |
          echo "release_tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "release_tag=${GITHUB_REF#refs/*/}"

      - id: previous_tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        run: |
          git fetch --prune --unshallow --tags
          echo tag=`git tag --list "v*" --sort=-version:refname --merged | head -n 2 | tail -n 1` >> $GITHUB_OUTPUT
          echo tag=`git tag --list "v*" --sort=-version:refname --merged | head -n 2 | tail -n 1`
          git tag --list "v*" --sort=-version:refname --merged

      - id: validate_tag
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: madhead/semver-utils@latest
        with:
          version: ${{steps.release_tag.outputs.release_tag}}
          compare-to: ${{steps.previous_tag.outputs.tag}}

      - if: github.event_name == 'push' && contains(github.ref, 'refs/tags') && steps.validate_tag.outputs.comparison-result == '>'
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: release-${{steps.release_tag.outputs.release_tag}}

      - if: github.event_name == 'push' && contains(github.ref, 'refs/tags') && steps.validate_tag.outputs.comparison-result == '>'
        uses: ncipollo/release-action@v1
        with:
          artifacts: release-${{steps.release_tag.outputs.release_tag}}
          tag: ${{steps.release_tag.outputs.release_tag}}
          generateReleaseNotes: ${{true}}
