name: Tag and Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Build Stage 
        run: 
          sbt stage
      - name: Zip
        run:
          echo "New tag is ${{ steps.tag.outputs.new_tag }}"
          echo "Previous tag is ${{ steps.tag.outputs.previous_tag }}"
          echo "Changelog is ${{ steps.tag.outputs.changelog }}"
           
